### ISSUE TITLE
[Solution]:Disqus not Working on Forked Websites.

### ISSUE THREAD

**Issue by ahmetcecen** [Materials-Informatics-Lab/research-pages#1]
**Problem:** You have edited the `_config.yml` file and added your Disqus name to the appropriate location. When you load your webpage at:

> yourname.github.io/research-pages

and you received the following message:

> We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

**Solution:** Go to [https://disqus.com/admin/create/](https://disqus.com/admin/create/). You might have to log in then click on this link again, you want to see the following:

![](http://matinfteam4.github.io/images/DisqusRegister.PNG)

and fill it as:
- **Site name:** `yourname.github.io/research-pages`
- **Disqus URL:** this is sort of a nickname for your **blog**. I used `yournameMatInf`. This is also your Disqus **Shortname** which you should write on the _shortname_ section on the __config.yaml_ file.
- **Category:** Doesn't really matter, I chose `Other`.

**Comment by tonyfast** [comment]
Thanks Ahmet.

**Comment by ashish173** [comment]
Thanks this helped me I was not using site unique name for shortname in my `_config.yml`

**Comment by tonyfast** [comment]
[From Disqus](https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions)

**Comment by davidbrough1** [comment]
Were you asked to "Choose your platfrom"? Does it matter?
![screenshot from 2014-12-11 14 05 16](https://cloud.githubusercontent.com/assets/4368625/5400060/d7c85ad2-813e-11e4-8f9f-1a97a52231ed.png)

**Comment by ahmetcecen** [comment]
No it doesn't it just gives you specialized embed codes for some platforms.
Universal code works on all of them.

**Comment by davidbrough1** [comment]
Thanks!

**Comment by tonyfast** [comment]
Choose embed link
